### ISSUE TITLE
Uncurstify doesn't complain about unmatched closed braces

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#842] opened 2016-11-30 15:29 UTC
This code:
```cs
namespace Namespace
{
	// class Class {
		public void foo()
		{

		}
	}
}
```

with this config:
```ini
indent_namespace                = true
indent_class                    = true
```

will be formatted just fine without any error to:
```cs
namespace Unity
{
	// class Class {
	public void foo()
	{

	}
}
}
```

even if I expected Uncrustify to fail with: `input/staging/brace_close.cs:9 Unmatched BRACE_CLOSE`.

**Comment by gmaurel** [comment] 2016-12-04 10:03
It is not the only point we should pointed to.
I/we are missing some tests which produce an(or more) error(s), and be sure
the errors protocol are still generated after any changes

**Comment by gmaurel** [comment] 2016-12-04 14:20
What do you think about that?
[indent_cpp-2.txt](https://github.com/uncrustify/uncrustify/files/629572/indent_cpp-2.txt)

**Comment by mihaipopescu** [comment] 2016-12-04 21:45
Yes. We need to modify/enhance the testing framework to support testing for errors as well. Maybe we can use (cram)[https://bitheap.org/cram/] for this.

The change looks good but I think we should take a look at `sysexits.h` and return a standardised error code.

**Comment by gmaurel** [comment] 2016-12-07 16:36
Making some changes I try to detect the BRACE_OPEN corresponding to the BRACE_CLOSE on your example.
By the way, I detect a problem with the file ```test/input/c/beautifier-off.c```
Looking backward with the function ```chunk_get_prev_type```, the line ```b = 2;``` as the type ```IGNORED``` because of the comment at line 17 ```/* *INDENT-OFF* */```
and so on backward. The ```{``` is not a BRACE_OPEN but a IGNORED. It cannot be found as the corresponding brace we are looking for. The function return ```NULL```.
Such a source cannot be properly proceeded.
Any proposal please!

**Comment by mihaipopescu** [comment] 2016-12-07 17:16
I don't really understand the new problem. Is the file tokenized improperly ? Can you paste the tokens map ?

**Comment by gmaurel** [comment] 2016-12-12 09:24
a bugfix is coming soon

**Comment by gmaurel** [comment] 2016-12-12 18:46
@mihaipopescu could you have a look to:
   ```https://travis-ci.org/uncrustify/uncrustify/jobs/183337507```
I cannot deal with the error.
What is to do?

**Comment by mihaipopescu** [comment] 2016-12-12 23:36
@gmaurel We need a compatibility header included if we don't `HAVE_SYSEXITS_H` which will be set by cmake if we add it in the `set(headers ...` list in CMakeLists.txt

**Comment by mihaipopescu** [comment] 2016-12-13 15:13
But in this case, I expected to return the `EXIT_FAILURE` exit code from the C standard. That's a different change we need to do later. Sorry for the confusion.

**Comment by mihaipopescu** [comment] 2016-12-13 15:15
I mean that, you'll see throughout the code exit with various exit codes that Ben used originally. We need to change them to use some standardized values like the ones from sysexits. Need a new issue for this.

**Comment by gmaurel** [comment] 2016-12-14 15:59
@mihaipopescu 
For reason(s) I don't anderstand there are many errors with the appveyor test.
The log is:
```
test 3
        Start   3: 10002
3: Test command: "C:\Program Files (x86)\CMake\bin\cmake.exe" "-DTEST_PROGRAM=C:/projects/uncrustify/build/Debug/uncrustify.exe" "-DTEST_LANG=cs" "-DTEST_CONFIG=config/ben.cfg" "-DTEST_RERUN_CONFIG=config/ben.cfg" "-DTEST_INPUT=input/cs/simple.cs" "-DTEST_RESULT=results/cs/10002-simple.cs" "-DTEST_OUTPUT=output/cs/10002-simple.cs" "-DTEST_DIR=C:/projects/uncrustify/tests" "-P" "C:/projects/uncrustify/tests/run_test.cmake"
3: Test timeout computed to be: 1500
3: CMake Error at C:/projects/uncrustify/tests/run_test.cmake:44 (message):
3:   Uncrustify error:
3: 
3: 
  3/666 Test   #3: 10002 ............................***Failed    0.35 sec
```
Can you have a look at this? Thanks.

**Comment by mihaipopescu** [comment] 2016-12-17 14:19
maybe @jibsen or @dirk-thomas can assist in this one. Do you see any error if you run the test locally or with the old `./run-tests.sh` script ?

**Comment by gmaurel** [comment] 2016-12-17 16:17
The problem is only present under windows.
I have only linux. I need some help from a window-fan!

**Comment by jibsen** [comment] 2016-12-17 19:26
@gmaurel this branch is crashing on Windows, due to using `pc` even though it is `NULL`, in the added `LOG_FMT` in `chunk_list.cpp` line 508.

**Comment by gmaurel** [comment] 2016-12-18 16:08
@jibsen Thanks to you for the error message.
The bug is now fixed.

**Closed by gmaurel** 2016-12-18 16:08 UTC
Labels: C and C++, C#, System
