### ISSUE TITLE
`indent_ternary_operator` not working correctly for ternary operator

### ISSUE THREAD

**Issue by samishchandra** [uncrustify/uncrustify#2546] opened 2019-11-21 08:53 UTC
### Input:
```
(options.meta == nil ? metaComponent
                     : ComponentBuilder()
  .direction(Row)
  .spacing(4);
```

### ✅Expected Output:
```
(options.meta == nil ? metaComponent
                     : ComponentBuilder()
                       .direction(Row)
                       .spacing(4);
```

### ❌Actual Output:
```
(options.meta == nil ? metaComponent
                     : ComponentBuilder()
  .direction(Row)
  .spacing(4);
```

### Config options used:
```
indent_columns = 2
indent_member = 0
indent_member_single = false
indent_ternary_operator = 2
```

### Uncrustify version
Uncrustify-0.70.0

**Comment by guy-maurel** [comment] 2019-11-21 17:30
same as #2545

**Comment by mwoehlke-kitware** [comment] 2019-11-21 18:32
Indeed; closing as a duplicate of #2545. @samishchandra, if you can show how this isn't a duplicate, feel free to reopen, but I have high confidence they're the same underlying issue.

**Closed by mwoehlke-kitware** 2019-11-21 18:32 UTC
Labels: Objective C
