### ISSUE TITLE
test_cli_options.sh does not exist and problems with test_cli_options.py

### ISSUE THREAD

**Issue by nivekkagicom** [uncrustify/uncrustify#1720] opened 2018-04-20 13:29 UTC
The readme makes reference to test_cli_options.sh:
> The Command line interface (CLI) output is tested by the test_cli_options.sh script. It is located inside of tests/cli/ and operates on the subdirectories of that folder.

However, this file does not appear in the distribution. Perhaps the readme should point to test_cli_options.py?

Also, with the current distribution I see the following from test_cli_options.py:
```
[uncrustify]# ./tests/cli/test_cli_options.py --diff
Uncrustify binary found: tests/cli/../../build/uncrustify

************************************
Problem with tests/cli/results/mini_d_error0.txt
************************************
"- tests/cli/config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"
'? ----------\n'
u"+ config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"

************************************
Problem with tests/cli/results/mini_d_error1.txt
************************************
"- tests/cli/config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"
'? ----------\n'
u"+ config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"

************************************
Problem with tests/cli/results/mini_d_error2.txt
************************************
"- tests/cli/config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"
'? ----------\n'
u"+ config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"

************************************
Problem with tests/cli/results/mini_d_error3.txt
************************************
"- tests/cli/config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"
'? ----------\n'
u"+ config/mini_d.cfg:2 Unknown symbol 'not_existing_option'\n"
some problem(s) are still present

```
Am I using the correct tool and if so any ideas why it is failing?

**Comment by CDanU** [comment] 2018-04-20 15:56
The `test_cli_options.sh` script was superseded by the python script.  I forgot to update the readme file.
The other issue is a duplicate of: #1677, I still haven't looked into that.

**Comment by gmaurel** [comment] 2019-03-01 17:22
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Closed** 2019-03-13 17:12 UTC
Labels: Engineering
