### ISSUE TITLE
nl_var_def_blk_start is ignored

### ISSUE THREAD

**Issue by RobertoBagnara** [uncrustify/uncrustify#3517] opened 2022-02-10 20:07 UTC
<pre>
$ uncrustify -v
Uncrustify_d-4dbe0768
</pre>
<pre>
$ cat p.cfg
nl_var_def_blk_start = 1
</pre>
<pre>
$ cat p.c
void g () {
  h();
  int x;
  return;
  {
    h();
    int x;
    return;
  }
}
</pre>
<pre>
$ uncrustify -c p.cfg p.c
Output suffix: .uncrustify
do_source_file(1505): Parsing: p.c as language C
</pre>
<pre>
$ cat p.c.uncrustify
void g () {
	h();
	int x;
	return;
	{
		h();
		int x;
		return;
	}
}
</pre>

The two occurrences of ``int x;`` are variable definitions not at the
top of a function body, hence they should be preceded by a blank line.

**Comment by BUGSENG** [comment] 2022-02-14 14:41
The cause seem to be similar to what fixed by PR #3535
Changing to nl_var_def_blk_start = 2 the newline is added.

**Closed** 2022-02-25 15:17 UTC
Labels: C and C++11
