### ISSUE TITLE
INDENT-OFF removes comments and removes indentation

### ISSUE THREAD

**Issue by HouwerDeGeus** [uncrustify/uncrustify#1275] opened 2017-07-12 20:10 UTC
Uncrustify 0.65
Please have a look at attached files.
After placing *INDENT-OFF* the comment line below is missing after beautifying.
Also the first indent in the non-beautified part is removed.

[ErrorIndentOnOff.zip](https://github.com/uncrustify/uncrustify/files/1143177/ErrorIndentOnOff.zip)

**Comment by mihaipopescu** [comment] 2017-07-13 06:09
Why not embed some snippets in the issue. Quite hard to see them on mobile.

**Comment by HouwerDeGeus** [comment] 2017-07-13 07:36
Sure. I did have some problems with copy-paste. The starts of comments /* were removed during paste.

Input:
![image](https://user-images.githubusercontent.com/30087231/28155357-9c36ff10-67ae-11e7-9184-6e08f7f88b5b.png)

Output:
![image](https://user-images.githubusercontent.com/30087231/28155376-b38eea2e-67ae-11e7-92ee-a446ca37a1d8.png)

**Comment by mihaipopescu** [comment] 2017-07-13 08:49
Oh, you mean with github markdown code syntax?

```
\`\`\`cpp
\`\`\`
```

**Comment by HouwerDeGeus** [comment] 2017-07-13 09:11
Hai, I mean /* was replaced by a single /.
Sorry I am not familiar with the best way of presenting the code in this comment window. This is the second time I place an issue. Therefore I made some pictures in the previous comment. So I would be glad if you tell me how this is done normally and I will try that the next time.

**Comment by mihaipopescu** [comment] 2017-07-13 10:32
Maybe this can help https://guides.github.com/features/mastering-markdown/ and you can edit your previously posted issue.

**Comment by CDanU** [comment] 2017-07-13 12:22
I think that is the same bug that you found last time. 

For now try without the options:
```sql
# Override the default ' *INDENT-OFF*' in comments for disabling processing of part of the file.
disable_processing_cmt          = ""         # string

# Override the default ' *INDENT-ON*' in comments for enabling processing of part of the file.
enable_processing_cmt           = ""         # string
```
As the description mentions they will default to the string that you have used in your code.

I will update my webtool when #1273 is merged in.

**Comment by HouwerDeGeus** [comment] 2017-07-13 17:23
Removing the option lines as mentioned works. Strange that "" is not stored as an empty string, since tokenizer.cpp checks for nullptr and '\0'. I used the 0.65 version, because I have not installed the Mingw compiler (yet), so I can't make the exe file of the last build currently (on Windows10). I will check if I can get the compiler.
I am testing your beautifier, because I have made a tool that partially generates C code and partially the user can edit peaces of code. I want to let the beautifier clean the user part and keep the generated code. Therefore I need to switch off and on the beautifier. Currently I use my own keywords for starting/ending the user code section. So I have to wait until the Indent on and off work with config settings like 
_disable_processing_cmt_  and _enable_processing_cmt_. Thanks for all the previous comments.

**Comment by mihaipopescu** [comment] 2017-07-13 18:32
You don't need mingw. If you have VisualStudio you can build with `cmake`.

**Comment by HouwerDeGeus** [comment] 2017-07-13 18:57
I was just creating a Visual Studio Community 2017 project. I saw that the file *token_names.h* is missing.
Am I right?

**Comment by CDanU** [comment] 2017-07-13 18:58
Some header files are generated by cmake.

**Comment by HouwerDeGeus** [comment] 2017-07-13 19:01
Ah, I see that file must be created by cmake. Ik will study how to do that.

**Comment by CDanU** [comment] 2017-07-13 19:55
> Installed cmake.
Created token_names.h
Created a new Visual studio Cpp console project. Added the source and header files.
Removed an error compiling uncrustify.cpp (complained about impossible cast to LPCWSTR on line 1350)
Ignored the warnings.
The project compiles.

That sounds somewhat overly complicated .. cmake should generate a solution (sln) file for you which you should use to compile everything without having to handle any header files.

The LPCWSTR is actually kinda also a bug ... it looks like it is a MS version for a wstring. We currently Uncrustify seems to handle only ASCII filepaths.

**Comment by HouwerDeGeus** [comment] 2017-07-13 20:00
For me this was faster than learning how to do that with cmake. But no problem. The result is the same I guess.

**Comment by mihaipopescu** [comment] 2017-07-14 06:27
To use mutibyte character strings is the default setting in VS when you create a new project. That's why is so much simpler to use cmake to generate your solution so that you can get started in seconds.

**Comment by HouwerDeGeus** [comment] 2017-07-14 17:33
Another strange behaviour with INDENT-ON and INDENT-OFF. If the first 3 lines are present line 11 and 28 do not indent:
**Input**
```
// *INDENT-ON*
/* Just some code or comment */
// *INDENT-OFF*
typedef struct XONESHOT_Context
{
    SE_GENERATOR_XONESHOT_CONTEXT_PARAMETERS
    SE_Char*                        pName;
    SE_UInt32                       delayMs;

// *INDENT-ON*
    TimerHandle_t xOneshotTimer;
// *INDENT-OFF*

} XONESHOT_Context;

static SE_Void inTrigger(
        SE_Context                          context                         )
{
    /* Variables  */
    XONESHOT_Context*               pContext                        = NULL;
// *INDENT-ON*
// *INDENT-OFF*

    /* retrieve context */
    pContext = ( XONESHOT_Context* ) context;

// *INDENT-ON*
	  xTimerStart(pContext->xOneshotTimer, 0);
// *INDENT-OFF*
}
```
**Output**
```
// *INDENT-ON*
/* Just some code or comment */
// *INDENT-OFF*
typedef struct XONESHOT_Context
{
    SE_GENERATOR_XONESHOT_CONTEXT_PARAMETERS
    SE_Char*                        pName;
    SE_UInt32                       delayMs;

// *INDENT-ON*
TimerHandle_t xOneshotTimer;
// *INDENT-OFF*

} XONESHOT_Context;

static SE_Void inTrigger(
        SE_Context                          context                         )
{
    /* Variables  */
    XONESHOT_Context*               pContext                        = NULL;
// *INDENT-ON*
// *INDENT-OFF*

    /* retrieve context */
    pContext = ( XONESHOT_Context* ) context;

// *INDENT-ON*
xTimerStart(pContext->xOneshotTimer, 0);
// *INDENT-OFF*
}
```
Let's leave out the first 3 lines:
**Input**
```
typedef struct XONESHOT_Context
{
    SE_GENERATOR_XONESHOT_CONTEXT_PARAMETERS
    SE_Char*                        pName;
    SE_UInt32                       delayMs;

// *INDENT-ON*
    TimerHandle_t xOneshotTimer;
// *INDENT-OFF*

} XONESHOT_Context;

static SE_Void inTrigger(
        SE_Context                          context                         )
{
    /* Variables  */
    XONESHOT_Context*               pContext                        = NULL;
// *INDENT-ON*
// *INDENT-OFF*

    /* retrieve context */
    pContext = ( XONESHOT_Context* ) context;

// *INDENT-ON*
	  xTimerStart(pContext->xOneshotTimer, 0);
// *INDENT-OFF*
}
```
**Output**
```
typedef struct XONESHOT_Context
{
    SE_GENERATOR_XONESHOT_CONTEXT_PARAMETERS
    SE_Char*  pName;
    SE_UInt32 delayMs;

// *INDENT-ON*
    TimerHandle_t xOneshotTimer;
// *INDENT-OFF*

} XONESHOT_Context;

static SE_Void inTrigger(
        SE_Context                          context                         )
{
    /* Variables  */
    XONESHOT_Context*               pContext                        = NULL;
// *INDENT-ON*
// *INDENT-OFF*

    /* retrieve context */
    pContext = ( XONESHOT_Context* ) context;

// *INDENT-ON*
    xTimerStart(pContext->xOneshotTimer, 0);
// *INDENT-OFF*
}
```
As you can see, the lines starting with _TimerHandle_ and _xTimerStart_ are indented.
This is the the way I would like to have it.

**Comment by CDanU** [comment] 2017-07-14 17:46
Confirmed, open op a new issue for this and close this one. 
Also use syntax coloring in the new issue for the code block, that makes it much more readable.
<pre>
```cpp
code code code
```
</pre>

**Closed** 2017-07-14 18:09 UTC
Labels: C and C++11
