### ISSUE TITLE
Parser gets hung up on macros which contain conditionals / complete expressions

### ISSUE THREAD

**Issue by zachriggle** [uncrustify/uncrustify#2813] opened 2020-06-13 22:01 UTC
Uncrustify fails to parse when it encounters macros which take code blocks as arguments, like this:

```c
#define macro_with_condition(a, b, c, d) if(!(a)) {c; puts(d); } goto b; 

int
function()
{
    int retval;
    int bar = 0;
    macro_with_condition(puts("always"), 
                         fail, 
                         retval = 1; if (bar) puts("if bar"),
                         "string"); 
fail:
    return retval;
}
```

I don't expect it to handle this gracefully as it's very odd, but it fails to parse the whole file when it runs into this.  I would expect that it just skips that particular line.  This happens with an empty configuration:

```
$ touch config
$ uncrustify -p debug.txt -c config -f err.c
Parsing: err.c as language C
parse_cleanup(446): pc->orig_line is 8, orig_col is 34, text() is ')', type is PAREN_CLOSE
parse_cleanup(448): (frm.top().type + 1) is VBRACE_CLOSE
parse_cleanup(454): File: err.c, orig_line is 8, orig_col is 34, Error: Unexpected ')' for 'VBRACE_OPEN', which was on line 7
parse_cleanup(446): pc->orig_line is 11, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(448): (frm.top().type + 1) is PAREN_CLOSE
parse_cleanup(454): File: err.c, orig_line is 11, orig_col is 1, Error: Unexpected '}' for 'PAREN_OPEN', which was on line 5
parse_cleanup(837): Unmatched BRACE_CLOSE
   orig_line is 11, orig_col is 1
parse_cleanup(844): Try the option 'tok_split_gte = true'
```

Version information:

```
$ uncrustify -v
Uncrustify-3357ad6
```

**Comment by gmaurel** [comment] 2020-06-14 14:29
Please push an compileable source.

**Comment by zachriggle** [comment] 2020-06-15 23:10
I have updated the original post with an example that compiles.

**Comment by CDanU** [comment] 2020-06-20 23:04
What a beauty ... you can ignore that behaviour by using the disable/enable comments:
```diff
diff --git 1/t.cpp 2/x.d
index 082fb94..516c775 100644
index 082fb94..516c775 100644
--- 1/t.cpp
+++ 2/x.d
@@ -5,12 +5,10 @@ function()
 {
     int retval;
     int bar = 0;
-    // *INDENT-OFF*
     macro_with_condition(puts("always"), 
                          fail, 
                          retval = 1; if (bar) puts("if bar"),
                          "string"); 
-    // *INDENT-ON*
 fail:
     return retval;
 }
\ No newline at end of file
```
That however still does not solve the underlying problem, most likely a closing vbrace is either not created or is not matching up with the created open vbrace for the if block.

**Comment by zachriggle** [comment] 2020-06-22 19:49
Aside from modifying the original code with macros like that, is there a way to get Uncrustify to simply continue with a possibly-broken state, OR to have it skip expressions that start with a given identifier?

**Comment by CDanU** [comment] 2020-07-12 14:43
We have options to set a string to a specific token (see [option.cpp:34](https://github.com/uncrustify/uncrustify/blob/affb083eecbbf99356cce8a944c8ba2962874402/src/option.cpp#L34)) but this won;t help you with this specific problem. Those comments above are the only thing that will help here. As suspected the problem is caused by the closing vbrace of the if block. We mark functions as such after all bace processing is done. Vbraces rely on `;` and `}` as termination chars. 

Basically it sets them this way:

```cpp
    macro_with_condition(puts("always"), 
                         fail, 
                         retval = 1; if (bar) { puts("if bar"),
                         "string"); }
```
As you can see now the closing paren of `macro_with_condition` is within the wrong scope and things go haywire. If you put a `;` after the puts the closing vbrace is set correctly. 

Uncrustify is set up to not be a compiler, we don't expand macros therefore we can't successfully deal with this kind of stuff.

**Closed by CDanU** 2020-07-12 14:43 UTC
Labels: C and C++11, breaking bug
