### ISSUE TITLE
Uncrustify won't output a debug file

### ISSUE THREAD

**Issue by dcommander** [uncrustify/uncrustify#1707] opened 2018-04-04 18:31 UTC
What am I doing wrong?  I tried 0.66_f from MacPorts, as well as a custom build from the current Git master branch.

_To reproduce:_
Create **test.c**:
```
#include <stdio.h>

int main(void)
{
	printf("Hello, World!\n");
	return 0;
}
```

```
uncrustify --update-config -o default.cfg
uncrustify -p debug.txt -c default.cfg test.c
```

_Expected behavior:_
debug.txt is generated

_Actual behavior:_
No debug file is generated

**Comment by dcommander** [comment] 2018-04-04 18:50
It seems that it works properly if I specify `-f test.c`, so that at least provides a workaround.  I still assert that this is a bug, however.

**Comment by CDanU** [comment] 2018-04-05 00:43
Duplicate of: #930

**Comment by guy-maurel** [comment] 2018-06-16 15:41
#930 is fixed.
Please test again and report

**Closed** 2018-11-09 17:40 UTC
Labels: Engineering, NoAnswer, waiting_for_answer
