### ISSUE TITLE
c# lambda => part is transformed to = > (insert space between = and >) that make c# compilation fail

### ISSUE THREAD

**Issue by plv2** [uncrustify/uncrustify#2118] opened 2018-11-29 14:28 UTC
c# lambda => part is transformed to = > (insert space between = and >) that make c# compilation fail

uncrustify 0.68.1
The no special uncrustify option to works as this

```
public SomeCode2()
{
    clientHandler.ServerCertificateCustomValidationCallback += ( sender, cert, chain, sslPolicyErrors ) => true;
}

public static string ToDetailedString( Exception exception, ExceptionOptions options )
{
    foreach ( PropertyInfo property in exception
                .GetType()
                .GetProperties()
                .OrderByDescending( x => string.Equals( x.Name, nameof( exception.Message ), StringComparison.Ordinal ) )
                .ThenByDescending( x  => string.Equals( x.Name, nameof( exception.Source ), StringComparison.Ordinal ) )
                .ThenBy( x            => string.Equals( x.Name, nameof( exception.InnerException ), StringComparison.Ordinal ) )
                .ThenBy( x            => string.Equals( x.Name, nameof( AggregateException.InnerExceptions ), StringComparison.Ordinal ) ) )
    {
        var  value = property.GetValue( exception, null );
    }

    return null;
}
```

become

```
public SomeCode2()
{
    clientHandler.ServerCertificateCustomValidationCallback += ( sender, cert, chain, sslPolicyErrors ) = > true;
}
public static string ToDetailedString( Exception exception, ExceptionOptions options )
{
    foreach( PropertyInfo property in exception
                .GetType()
                .GetProperties()
                .OrderByDescending( x = > string.Equals( x.Name, nameof( exception.Message ), StringComparison.Ordinal ) )
                .ThenByDescending( x  = > string.Equals( x.Name, nameof( exception.Source ), StringComparison.Ordinal ) )
                .ThenBy( x            = > string.Equals( x.Name, nameof( exception.InnerException ), StringComparison.Ordinal ) )
                .ThenBy( x            = > string.Equals( x.Name, nameof( AggregateException.InnerExceptions ), StringComparison.Ordinal ) ) )
    {
        var  value = property.GetValue( exception, null );
    }

    return stringBuilder.ToString().TrimEnd( '\r', '\n' );
}
```

[UncrustifyCodeSample.zip](https://github.com/uncrustify/uncrustify/files/2629472/UncrustifyCodeSample.zip)

**Comment by coeo** [comment] 2018-12-07 04:49
Similar to #1121.
Fixes: #1133, and f6489898d96086db3d308040b4679cfc1889851c for '->' and '::' in Java.

Weird, because [src/symbols_table.h already has "LANG_CS" for "=>" ](https://github.com/uncrustify/uncrustify/blob/1a41fd92e7cdf866f612a4e9115d99f7bcf0bd45/src/symbols_table.h#L106)

**Comment by coeo** [comment] 2018-12-07 09:04
Unable to reproduce.

Ran:

```sh
~/workspace/uncrustify/build (csharp-lambda-bugfix) $ \
./uncrustify -c uncrustify.cfg -f SomeCode_Ori.cs | grep '=\s*>'
```

with the two provided build files and got:

```csharp
            clientHandler.ServerCertificateCustomValidationCallback += ( sender, cert, chain, sslPolicyErrors ) => true;
                      .OrderByDescending( x => string.Equals( x.Name, nameof( exception.Message ), StringComparison.Ordinal ) )
                      .ThenByDescending( x => string.Equals( x.Name, nameof( exception.Source ), StringComparison.Ordinal ) )
                      .ThenBy( x => string.Equals( x.Name, nameof( exception.InnerException ), StringComparison.Ordinal ) )
                      .ThenBy( x => string.Equals( x.Name, nameof( AggregateException.InnerExceptions ), StringComparison.Ordinal ) ) )
```

The lambda '=>'s are intact.

**Comment by plv2** [comment] 2018-12-07 10:14
With this config, I also cannot reproduce it. Please, let me check into my git history of my config file to identify the concerned option that I have removed to turn around the problem.  I will try to do it today.
Thanks for your answer.

**Comment by CDanU** [comment] 2018-12-08 22:53
Can't reproduce this on addeec9, I do get this issue however if the code is treated as C++.

So everything works as expected, closing it for now.

**Closed by CDanU** 2018-12-08 22:53 UTC
Labels: C#
