### ISSUE TITLE
Nl_remove_extra_newlines segfaulting

### ISSUE THREAD

**Issue by Massimo-B** [uncrustify/uncrustify#369] opened 2015-04-22 12:02 UTC
This is uncrustify 0.61.

I get a segfault with this source...
```bash
$ uncrustify -q -l cpp -c ~/.uncrustify.cfg -f crusty-test.cpp 
```
```cpp
void Response::write( QString const &_fileName ) {
QDomElement     root = m_responseDoc.createElement( "Message" );

root.appendChild( getNodeMessageBody() );
	QFile       outFile( _fileName );

	if( !outFile.open( QIODevice::WriteOnly | QIODevice::Text ) ) {
		return false;
	}
	QTextStream stream( &outFile );
	outFile.close();
}
```
...and this configuration:
https://bitbucket.org/massimo/configs/raw/14235d0d695a82cfa48db4e3bc980e9fbf46b3af/.uncrustify.cfg

The bug is about Nl_remove_extra_newlines:
0: works
1: segfault
2: works

**Comment by sjakub** [comment] 2016-06-20 23:36
Possibly my issue ( #518 ) is related to this one?

**Comment by gmaurel** [comment] 2016-07-04 08:36
Works for me

**Comment by sjakub** [comment] 2016-07-04 18:33
Just FYI, it would be crashing if there was an empty line at the beginning of the input file and nl_remove_extra_newlines = 1

**Comment by gmaurel** [comment] 2016-07-20 12:51
I cannot reproduce.
Can you give more information? Operating system, version, crash info!

**Comment by sjakub** [comment] 2016-07-20 13:37
I'm pretty sure this is now fixed. In this change: #520 .
It was hard to reproduce, adding or removing characters in names, etc. was changing the behaviour.
But running uncrustify through valgrind was showing this issue even without the crash.
The key was one empty line at the beginning of the file.

**Closed** 2016-07-20 16:51 UTC

**Comment by Massimo-B** [comment] 2016-07-21 06:09
I can't reproduce either anymore. Seems to be fixed. Thanks.
