### ISSUE TITLE
multiplication operator '*' misinterpreted as pointer operator

### ISSUE THREAD

**Issue by uwerat** [uncrustify/uncrustify#2152] opened 2019-01-04 16:03 UTC
Using origin/master f72c97d40761ecdd963dfc8cf2b17a900f30ebb3 ( 19/01/04 ) with the following option:
```
sp_before_ptr_star              = remove
```
Code:
```
void f()
{
	const double ratio = 2.0;
	const Rect r( 0.0, 0.0, ratio * size().width(), ratio * size().height() );
}
```
In the result the space in front of the '*' operators gets removed as if it is was interpreted as a pointer:
```
void f()
{
	const double ratio = 2.0;
	const Rect r( 0.0, 0.0, ratio* size().width(), ratio* size().height() );
}
```

**Comment by guy-maurel** [comment] 2019-05-22 16:57
PR #2301 is a bugfix proposal.
Please test it and report.

**Comment by chris-mich** [comment] 2019-06-19 20:42
Went into the same problem here with version 0,69

```
void test()
{
	CPoint pt( a * b, a * b, a * b );
}
```

Result:
```
void test()
{
	CPoint pt( a * b, a* b, a* b );
}
```

**Comment by guy-maurel** [comment] 2019-07-28 16:25
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
```.txt
Uncrustify-0.69.0-62-97602cbc-dirty
void test()
{
        CPoint pt( a * b, a * b, a * b );
}
```

**Comment by chris-mich** [comment] 2019-07-30 19:40
OK, I will retest when version 0.70 will be released.  Thank you! ;-)

**Comment by gmaurel** [comment] 2019-07-31 15:45
This will be mid November 2019

**Comment by chris-mich** [comment] 2021-07-13 20:51
There is a regression in version 0.73, this bug is back, also with a simplier case like the following:

`CPoint pt( a * b );
`

becomes:

`CPoint pt( a* b );`

**Comment by guy-maurel** [comment] 2021-07-14 15:24
```.txt
Uncrustify_d-0.73.0-76-a6df3c5c
CPoint pt( a * b );
```

The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by chris-mich** [comment] 2021-07-14 15:36
Config:

```
# Uncrustify-0.73
sp_before_ptr_star = remove
```

Input:
```
void Func()
{
    CTPoint pt( a * b );
}
```

Output:
```
void Func()
{
    CTPoint pt( a* b );
}
```

I downloaded 0.73 Win64.  This problem was fixed in 0.70, but came back in 0.73.

**Comment by gmaurel** [comment] 2021-07-20 16:06
@chris-mich 
The question might be trivial (sorry)
What is/are the differences:
a)
```cpp
CTPoint pt( a* b );
```
b)
```cpp
void Func()
{
    CTPoint pt( a* b );
}
```
Is it a declaration of pt?
Is CTPoint a type?
What is a?
What is *?

**Comment by chris-mich** [comment] 2021-07-21 15:30
I agree with you, this is not a simple problem. But it used to work just fine in version 0.71, I don't know how you did it! :)

**Comment by chris-mich** [comment] 2021-07-28 20:06
Typically:

a) **CTPoint** is the return type, **pt** is the function name, **a*** is the argument type, **b** is the argument.
b) **CTPoint** is the variable type, **pt** is the variable name, **a** and **b** are other variables, and * is the multiplication operator.

But:

a) can be a function declaration or a global variable definition, I'm not sure that Uncrustify can make the difference...
b) is a definitely variable definition, since we are in the scope of a function.

Hope this helps!

**Comment by chris-mich** [comment] 2021-07-28 20:12
To simplify, we can get rid of CPoint, witch is always a type.

```
void Function()
{
    int a( 0 );
    int b( 0 );
    int c( a * b );
}
```

**Comment by guy-maurel** [comment] 2021-12-16 17:31
Just now, 0.74 we have:
```.txt
# Line                Tag         Parent_type  Type of the parent         Columns Br/Lvl/pp       Flag   Nl  Text
#   1>               TYPE|         FUNC_PROTO|     PARENT_NOT_SET[  1/  1/  7/  0][0/0/0][       e0000][0-0] CPoint
#   1>         FUNC_PROTO|               NONE|     PARENT_NOT_SET[  8/  8/ 10/  1][0/0/0][           0][0-0]        pt
#   1>        FPAREN_OPEN|         FUNC_PROTO|     PARENT_NOT_SET[ 10/ 10/ 11/  0][0/0/0][   200000000][0-0]          (
#   1>               TYPE|               NONE|     PARENT_NOT_SET[ 12/ 12/ 13/  1][0/1/0][      880008][0-0]            a
#   1>           PTR_TYPE|               NONE|     PARENT_NOT_SET[ 13/ 14/ 15/  1][0/1/0][   200000008][0-0]             *
#   1>               WORD|               NONE|     PARENT_NOT_SET[ 15/ 16/ 17/  1][0/1/0][     1080008][0-0]               b
#   1>       FPAREN_CLOSE|         FUNC_PROTO|     PARENT_NOT_SET[ 17/ 18/ 19/  1][0/0/0][   200000008][0-0]                 )
#   1>          SEMICOLON|         FUNC_PROTO|     PARENT_NOT_SET[ 18/ 19/ 20/  0][0/0/0][   200000000][0-0]                  ;
```

**Closed** 2024-04-23 14:55 UTC
Labels: C and C++11
