### ISSUE TITLE
[Feature Request] Function Call Argument Indent

### ISSUE THREAD

**Issue by jwhui** [uncrustify/uncrustify#1100] opened 2017-04-06 17:50 UTC
I am trying to use uncrustify to automatically split function call parameters onto separate lines.  I have successfully gotten it to do that, but I would like the parameters aligned one indent in from the function name/close paren.  Is this possible to do?  I'm using v0.64.

See examples below.

Actual:
```c++
    int res = SEGGER_RTT_ConfigUpBuffer(
        LOG_RTT_BUFFER_INDEX,
        LOG_RTT_BUFFER_NAME,
        sLogBuffer,
        LOG_RTT_BUFFER_SIZE,
        SEGGER_RTT_MODE_NO_BLOCK_TRIM
              );
```

Desired:
```c++
    int res = SEGGER_RTT_ConfigUpBuffer(
                  LOG_RTT_BUFFER_INDEX,
                  LOG_RTT_BUFFER_NAME,
                  sLogBuffer,
                  LOG_RTT_BUFFER_SIZE,
                  SEGGER_RTT_MODE_NO_BLOCK_TRIM
              );
```

**Comment by CDanU** [comment] 2017-04-06 17:52
Post your current config.

**Comment by jwhui** [comment] 2017-04-06 18:00
Config: 
[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/903534/uncrustify.txt)

**Comment by jwhui** [comment] 2017-04-06 18:00
Config: [uncrustify.txt](https://github.com/uncrustify/uncrustify/files/903535/uncrustify.txt)

**Comment by CDanU** [comment] 2017-04-06 18:39
Hmm I get you result with:
```sql
# The original size of tabs in the input. Default=8
input_tab_size                  = 4        # unsigned number

# The size of tabs in the output (only used if align_with_tabs=true). Default=8
output_tab_size                 = 4        # unsigned number

#
# Indenting
#

# The number of columns to indent per level.
# Usually 2, 3, 4, or 8. Default=8
indent_columns                  = 4        # unsigned number

# The continuation indent for func_*_param if they are true.
# If non-zero, this overrides the indent.
indent_param                    = 10       # unsigned number

# How to use tabs when indenting code
# 0=spaces only
# 1=indent with tabs to brace level, align with spaces (default)
# 2=indent and align with tabs, using spaces when not on a tabstop
indent_with_tabs                = 0        # number

# True:  indent continued function call parameters one indent level
# False: align parameters under the open paren
indent_func_call_param          = true     # false/true

# Double the indent for indent_func_xxx_param options
indent_func_param_double        = true     # false/true

# Controls the indent of a close paren after a newline.
# 0: Indent to body level
# 1: Align under the open paren
# 2: Indent to the brace level
indent_paren_close              = 2        # unsigned number
```
but that seems overly complicated and brittle.

**Comment by jwhui** [comment] 2017-04-06 19:01
I must be missing something, but `indent_param` is not recognized by my version of uncrustify.

```bash
$ uncrustify --version
uncrustify 0.64
$ uncrustify -c uncrustify.cfg
uncrustify.cfg:55 Unknown symbol 'indent_param'
```

In any case, does `indent_param = 10` hardcode the continuation indent to 10 spaces?  What I'm actually looking for is to set the continuation indent to be the same as close paren.

**Comment by CDanU** [comment] 2017-04-06 19:24
It might be that your release version does not have `indent_param`. 
Yes this should be considered as feature request.

**Comment by jwhui** [comment] 2017-04-06 19:26
I used 0.64 from https://github.com/uncrustify/uncrustify/archive/uncrustify-0.64.tar.gz

**Comment by guy-maurel** [comment] 2017-05-09 15:06
The option` indent_param` is introduced 2017  Feb 01
If you want to use it you need to get it from the git.
  _https://github.com/uncrustify/uncrustify_
Please test it and report!
We plan a new release (0.65) soon.

**Comment by jwhui** [comment] 2017-05-09 17:55
@guy-maurel, @CDanU noted the limitation of using `indent_param` in his comment above.  Has this limitation been addressed?

**Comment by CDanU** [comment] 2017-05-09 18:05
Personally I hadn't done anything on this issue yet or on the `indent_param` option, and I didn't recall any changes by someone else. 

Currently I am working on a more critical bug and while doing so got a bit sidetracked by adding new options for list initializers preceded by a type: `auto i = uint{3};`
After that I plan to tackle another critical issue and than the new release should be done this month. A fix for your issue unfortunately will therefore be released with release 0.66 or later.

**Comment by jwhui** [comment] 2017-05-09 18:13
@CDanU, thanks for the update.

@guy-maurel, I think it's safe to say that this issue is not resolved.

**Comment by guy-maurel** [comment] 2017-05-15 15:26
The limitation is 16.
Have you made a test as proposed?

**Comment by jwhui** [comment] 2017-05-15 16:08
@guy-maurel, the test is outlined in my original post.

@CDanU posted the following remark:

> E: yes it will brake if you change the name of you var. I guess there is no option combination currently to get this.

I also posted the following clarification on the requirement:

> In any case, does indent_param = 10 hardcode the continuation indent to 10 spaces? What I'm actually looking for is to set the continuation indent to be the same as close paren.

Having a fixed absolute indent is not what I'm looking for.  I'm looking for an indent relative to the close paren.

**Comment by guy-maurel** [comment] 2017-10-16 17:42
With the current version you get:
```
Parsing: jwhui.cpp as language CPP
int res = SEGGER_RTT_ConfigUpBuffer(
              LOG_RTT_BUFFER_INDEX,
              LOG_RTT_BUFFER_NAME,
              sLogBuffer,
              LOG_RTT_BUFFER_SIZE,
              SEGGER_RTT_MODE_NO_BLOCK_TRIM
          );
```
Please test again and report.

**Comment by akrishna03** [comment] 2017-10-25 12:30
Hi. I'm using uncrustify to fix the indents. 
When running on my mac, it works fine. But when i shift it to docker, I get unknown symbol error for a bunch of instructions in the config file.
I checked, and the version of uncrustify is same in both. `Uncrustify-0.65_f`

Can anyone help me understand what the issue is?
[errors_uncrustify.txt](https://github.com/uncrustify/uncrustify/files/1414533/errors_uncrustify.txt)

**Comment by gmaurel** [comment] 2017-12-01 17:35
No more answer. I close.

**Closed by gmaurel** 2017-12-01 17:35 UTC
Labels: C and C++11, NoAnswer, waiting_of_answer
