### ISSUE TITLE
Uncrustify crashes with *INDENT-OFF*

### ISSUE THREAD

**Issue by svart-riddare** [uncrustify/uncrustify#1478] opened 2017-12-06 08:07 UTC
Using uncrustify 0.65 (on Windows), with the default configuration file and the following input :

```
namespace n
{
// *INDENT-OFF*
}
```

Uncrustify crashes after printing

> flag_parens: no match for [{] at [zu:zu] [CallStack:-DEBUG NOT SET-]

**Comment by guy-maurel** [comment] 2017-12-06 18:51
This is not a bug.
After `// *INDENT-OFF*` all is ignore until `// *INDENT-ON*`.
The closing brace cannot be found.

**Comment by svart-riddare** [comment] 2017-12-07 10:53
Yes, I understand that the closing brace is missing; nevertheless the software should not crash.

With the following input,
```
namespace n
{
```
it prints the same error but does not crash.

**Comment by guy-maurel** [comment] 2017-12-07 16:55
It is not a crash but an error message.

**Comment by svart-riddare** [comment] 2017-12-08 08:16
On Windows :

![image](https://user-images.githubusercontent.com/16391865/33756963-45917f96-dbf8-11e7-88d4-d08e7cc13e4a.png)

**Comment by guy-maurel** [comment] 2017-12-08 08:55
It might be an incorrect message building under windows. I don't have experience. The c++ code is:
```
      LOG_FMT(LERR, "%s(%d): no match for '%s' at [%zu:%zu]",
              __func__, __LINE__, po->text(), po->orig_line, po->orig_col);
      log_func_stack_inline(LERR);
      cpd.error_count++;
      return(nullptr);
```
Somewhere else (uncrustify.cpp:813) the `cpd.error_count` is evaluate to produce exit the program:
```
   if (cpd.error_count != 0)
   {
      return(EXIT_FAILURE);
   }
```
The file `error_types.h` define some error for windows.
Do you konow the right value for `EXIT_FAILURE` ? or any better solution(s) for that?
Thanks et bonne journée

**Comment by svart-riddare** [comment] 2017-12-11 13:39
I'll have a go at running the code in debug mode later this week.

**Comment by gmaurel** [comment] 2017-12-11 14:29
Fine.

**Closed by gmaurel** 2017-12-11 14:29 UTC
Labels: C and C++11

**Comment by svart-riddare** [comment] 2017-12-13 09:03
Built and ran the current source tree on Windows, crash is not reproduced (and error message has changed, I no longer have `[zu:zu]` but `[2:1]` in the error string).

Tried with tag _uncrustify-0.65_ but cmake process fails to find Python; I am stopping investigations here as you have already closed the issue.
