### ISSUE TITLE
Indentation of Objective-C Dictionary/Array literals when used as Parameter not as expected

### ISSUE THREAD

**Issue by clausweymann** [uncrustify/uncrustify#1866] opened 2018-07-09 11:23 UTC
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
I'm trying to find the setting to indent my code and I'm stuck.
```objc
- (IBAction)testMethod:(id)sender
{
	NSDictionary* test = @{
		@"key1": @"value1",
	};
	[MyClass doSomethingWithParameters:@{
		@"key1": @"value1",
	}];
}
``` 

gets formatted to :
```objc
- (IBAction)testMethod:(id)sender
{
	NSDictionary *test = @{
		@"key1": @"value1",
	};
	[MyClass doSomethingWithParameters:@{
	 @"key1": @"value1",
	}];
}
``` 

expected would be
```objc
- (IBAction)testMethod:(id)sender
{
	NSDictionary *test = @{
		@"key1": @"value1",
	};
	[MyClass doSomethingWithParameters:@{
		@"key1": @"value1",
	}];
}
``` 
[debug.txt](https://gist.github.com/clausweymann/39384f2b7c4128274de1223c338e539e)

I think by now I tried all options that would make sense (with prefix indent_*) but only managed to remove the one space indentation. So I'm pretty convinced it's a bug/ missing feature. Thanks for your help and for all your effort you put in this great tool!

**Comment by nivekkagicom** [comment] 2018-07-09 11:39
FWIW this is the same problem that was fixed by PR #1828

**Comment by cweymann** [comment] 2018-07-09 15:33
Cool, Thanks! That actually seems to work as intended. For the time being I'll use a fork with your changes.

**Comment by guy-maurel** [comment] 2019-04-04 15:39
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by cweymann** [comment] 2019-05-08 14:44
It does, if you set "indent_continue = 4".
With the provided configuration the current version would indent too much:
```objc
- (IBAction)testMethod:(id)sender
{
	NSDictionary *test = @{
			@"key1": @"value1",
	};
	[MyClass doSomethingWithParameters:@{
		 @"key1": @"value1",
	}];
}
```
I still don't quite understand why though.
Anyway, thank you!

**Closed** 2019-06-10 09:23 UTC
Labels: Objective C
