### ISSUE TITLE
recursive search for files

### ISSUE THREAD

**Issue by jayvdb** [uncrustify/uncrustify#639] opened 2016-08-21 09:15 UTC
Continuing/cloning https://sourceforge.net/p/uncrustify/feature-requests/149/ and https://sourceforge.net/p/uncrustify/feature-requests/146/ ..

It would be helpful if there was a single `uncrustify` command line that can be used on either unix or Windows, that processes all the relevant files.

The biggest problem to solve is deciding how to avoid descending into non-code directories, especially VCS directories.

Other tools like `astyle` often solve that problem while also solving the "which files to process" problem by having a file glob path which indicates which paths to follow and which file extensions to process.

A forward compatible (and clean-backwards-breaking) minimal and simple solution is to only allow the user to specify the directory names that contain code (e.g. `src/` or `.`) and let uncrustify process all files that match typical file extensions.

**Comment by mihaipopescu** [comment] 2016-08-21 21:32
We don't have to unjustifiably increase the complexity of the code. You can have a simple wrapper script that does this (think about Python or Perl if you want portability). Could this work for you?

**Comment by jayvdb** [comment] 2016-08-22 03:51
Adding new functionality that is orthogonal to existing functionality does
not increase complexity, unless it is very badly coded, but it increases
scope.
IMO, this scope already implicitly exists - Recursive invocation is a
normal use case of uncrustify.
You already get support issues relating to invoking uncrustify with
external tools like find/xargs, and those tools are different on each OS,
and missing on one of your users most common OS.
By adding a poor performing but simple directory entry scanner you then
have a simple & supportable answer for how to do recursive file selection.
Then advanced users may want to improve perf by using better OS specific
tools (like find and xargs), but then they do not need to be supported.

Would you accept a cross-platform Python wrapper into this repo?

**Comment by mihaipopescu** [comment] 2016-08-22 10:08
> Adding new functionality that is orthogonal to existing functionality does not increase complexity, unless it is very badly coded, but it increases scope.

I totally agree. When I was talking about the complexity I was actually thinking about increasing the scope. Thanks for clarifying. On the other hand, we've already had some platform specific issues (like special handling of `rename` on Windows). Having a reduced focused scope is key having to deal with less new issues and less new feature requests in the future.

> IMO, this scope already implicitly exists - Recursive invocation is a normal use case of uncrustify.

Yes but not necessarily. Uncrustify has a lot of use-cases. Some may use it though an IDE extension and some may use the batch feature. Recursive invocation is a normal use-case if you're planning to format an entire code base for instance. Another use-case would be that you may want to hook uncrustify on a VCS to process all modified files for instance. I don't have any statistics so I can't say which use-case is mostly used but I guess in any case you'll end up writing wrapper scripts anyways to be able to handle more complicated scenarios of your particular code base or needs.

> You already get support issues relating to invoking uncrustify with external tools like find/xargs, and those tools are different on each OS, and missing on one of your users most common OS.

Maybe, I'm not aware of that.

> By adding a poor performing but simple directory entry scanner you then have a simple & supportable answer for how to do recursive file selection.

Ok but think about maintaining that in the future. Having this new feature is like an invitation for more feature requests and support tickets (eg. _exclude hidden and executable files with size less than 10 MB that are not under revision control but not older than 3 months_). I know it's a contrived example but queries tend to complicate over time. That's the main reason why they should remain to be handled on the user side.

> Would you accept a cross-platform Python wrapper into this repo?

I don't think portability of helper scripts was the initial intention of the authors as there are some shell scripts like `etc/dofiles.sh` or `etc/uncrust-files.sh`. The development was done on one platform (probably some flavour of Linux?) and cross-compiled on the others. Nowadays, I've also observed a tendency to migrate towards Python for Uncrustify helper scripts. There are already Python scripts in the repo so I guess patches with Python scripts are welcome.

**Comment by jayvdb** [comment] 2016-08-25 13:48
Is there a list of existing wrappers/recipes in other repos, or is Universal Indent GUI the only one?

**Comment by mihaipopescu** [comment] 2016-08-25 14:18
I don't know... but it should be quite easy to write one from scratch. See https://docs.python.org/2/library/os.html#os.walk and do your filtering there based on what you need.

**Comment by CDanU** [comment] 2016-12-26 16:35
#725 is a duplicate of this

**Closed** 2017-04-20 16:58 UTC
Labels: System
