### ISSUE TITLE
extern "C" { } not matched

### ISSUE THREAD

**Issue by codable** [uncrustify/uncrustify#1196] opened 2017-06-05 06:27 UTC
found in latest release 0.65.

debug file: test.h
```cpp
#ifdef __cplusplus
extern "C" {
#endif


void test(void);

#ifdef __cplusplus
} // extern "C"
#endif
```
run uncrustify,
```sh
$ uncrustify --version
Uncrustify-0.65
$ uncrustify -c forUncrustifySources.cfg test.h
Output suffix: .uncrustify
Parsing: test.h as language CPP
Unmatched BRACE_CLOSE
at line=9, column=1
```
current version: uncrustify 0.65
working version: uncrustify 0.64

**Comment by codable** [comment] 2017-06-05 10:18
I think this is related to [Known Problems](https://github.com/uncrustify/uncrustify/wiki/Known-Problems).
The situation described above is very common usage in c++ project. This issue blocks using the latest 0.65 version.

**Comment by dirk-thomas** [comment] 2017-06-06 19:08
I have the same problem (I tried the current master). This is a regression blocking us to move forward to the current version.

**Comment by markh-de** [comment] 2017-06-27 12:56
Same here. This is also blocking our company from using the latest uncrustify release, unfortunately.

From a technical standpoint, I understand the parser's dilemma. How should it properly indent content that is placed between non-constant-conditional curly braces.

But I have to agree with @codable. As ugly as it is (well, we're talking about C/C++), this is common practice for C APIs (we have hundreds of occurrences in our code base), so uncrustify should _really_ be able to handle this. E.g., simply be ignoring asymmetric (unmatched) curly braces within PP-conditions or something like that. Following the error message, it seems to (partially?) do that already. Because: It complains about an unmatched closing brace, while the condition for the opening and closing brace is exactly the same. So if it sees and processes the one brace, why did it not see and process the other one?

On the user side, this issue can be worked around by guarding the closing brace with ```/* *INDENT-OFF* */``` and ```/* *INDENT-ON* */```, but if I merge this to our master, my boss is going to rip my head off. Same for using ```BEGIN_...```/```END_...``` macros.

So, what do you think ... Will this issue be addressed anytime soon? Or should I start hacking a pre-/postprocess script that applies and removes the above workaround guards?

Thank you in advance!

**Comment by CDanU** [comment] 2017-06-27 16:12
I know that, this is problematic. I plan to fix that issue so it is not included in the next release. As we plan to hold (a not too strictly) a release cycle of 6 months that will take a while.
A proper solution for this will most likely be finished earlier than that (absolutely no promises) but in the meantime you could try to see how much havoc actually is caused by removing the closing brace check in: [brace_cleanup.cpp:L700-L707](https://github.com/uncrustify/uncrustify/blob/0f5a5577b6ff8ebb151a01c88ffb24902d00097f/src/brace_cleanup.cpp#L700-L707)
Atually I am somewhat inclined to rewrite the whole functionality of that file.

Btw.: I do hope to get some PRs if you guys start dealing with the code :).

**Comment by pkolbus** [comment] 2017-07-05 02:19
I'm seeing no problems (same behavior as 0.64) after removing the check, although guarding it with a pp_level check keeps a modicum of robustness. And based on parse_cleanup() this lack of problems is not unexpected (no dangling BRACE_OPEN in the stack because that was cleaned out by processing the first #endif). If you like I can make a test case and PR for this.


Also of note-- IMO it's generally a bad idea to have compiler and preprocessor scopes overlap -- the extern C is one narrow useful case. Overlapping scopes does have edge cases that can get complex quickly for a parser that's not #define aware. One off the top of my head:

    #if FOO || BAR
    if( baz )
    {
    #endif
    #if FOO
        stuff();
     }
    #elif BAR
    }
    bar_unconditional_stuff();
    #endif

**Comment by guy-maurel** [comment] 2017-07-12 15:44
Let me remember what _uncrustify_ wanted to do: A code **beautifier**.
I will be very happy if we could achieve that all correct sources could be recognized and properly formatted with _uncrustify_.
The next goal is C++11, following by 14, 17 and C++20 ...
Errors and warnings are at the best generated by compilers, for example _clang_.
It is not a job for us at _uncrustify_.
The most of issues we get the last months are caused by parsing errors.
This is done by `tokenize`, `tokenize_cleanup`, `brace_cleanup`, `fix_symbols`, `mark_comments`, `combine_labels`, `combine` and some more.
It would be fine to use some functions from _clang_ to do the job.
On this way, many of our problems would be solved.

Is there anybody to help this way?

**Comment by pkolbus** [comment] 2017-07-12 21:43
I think that makes a lot of sense and would be happy to help in that direction. Sounds like it may be a big job and perhaps some months, maybe not even for 0.66.  Short term, how about I fully remove that fatal error from brace cleanup, so we are prepared for another release, those who do build from source are not burned by this, and we have a test case for it?

I’ll get something up tonight.

**Comment by mihaipopescu** [comment] 2017-07-13 06:07
I agree even though the release cycle is every 6 months or so.

**Closed** 2017-07-16 15:12 UTC
Labels: C and C++11
