### ISSUE TITLE
Replacing pointers by const references.

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#1401] opened 2017-10-27 23:26 UTC
Unfortunately pointers are currently used almost everywhere inside the source code.
I think that pointers should only be used if it is useful to have `nullptr` values (or changing the location the pointer points at). This is not the case for most of Uncrustifys functions.

I would like to propose to change __every__ function that _needlessly_ uses pointer parameters into using references instead. In a second step I would like to add `const` correctness to some of those functions.

The changes would be done on a file by file basis, starting with functions that have the least amount of references (for example in _spaces.cpp_ that would be `space_text()`). 
In each function the then unnecessary `nullptr` (and the previously added assert, _see next sentence_) checks will be removed. 
Every function that references the modified function will (temporarily) get assert instructions (or if/else blocks?) to protect the needed dereferencing of parameters in order to pass them to the modified function.

The problem that I am seeing in this approach is, that that will generate tons of commits. Cumulatively they will (most likely) touch _all_ functions. I can't really submit that into one PR as this will take took much time and I will constantly get merge conflicts (also submitting one ginormous PR is a bad idea anyways). I would submit one PR for each function. This still undoubtedly will cause some merge conflicts that won't affect only my work but also other simultaneously submitted PRs (, we also would diverge even more from the unity fork). 

If this is done the end result will be that we will have to care about `nullptr` values in fewer places. Dereferencing those is still a problem that we have. Additionally the const correctness will hopefully prevent some mistakes in the future. 

What do you think of this?
@gmaurel, @mihaipopescu and whoever else reads this.

**Comment by mihaipopescu** [comment] 2017-10-29 11:04
I salute your initiative!

Changing from pointers to references seems like a very big change with possible implications (like more memory copying... maybe need to consider adding move sematics to classes? I don't know).

Why not start simply by using [not_null\<T\>](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-nullptr). With this you can ensure that pointers are never going to be null and you can remove useless nullptr checks without a major change to the codebase. 

To avoid a lot of manual work, maybe you can consider a refactoring tool like [clang-refactor](https://clang.llvm.org/docs/RefactoringEngine.html) so you can do it across all files.

**Comment by CDanU** [comment] 2017-10-29 14:24
Changing from pointers to references should't be too much of a deal. I get conflicting information about that on the web but as far as I know nothing in the standard specifies how references are implemented. Apparently most of the times they are just pointers in disguise that can't be `nullptr`. References don't create new copies of data. 
Most pointers in the code are passing around the `chunk_t` tokens from the `ChunkList_t`. Move semantics can't be applied as the tokens have to remain in the list. Surely somewhere in the code move semantics could be applied, but that would be its own refactoring step.
While the GSL is certainly a nice library, because of the points I made about references I don't really see the reason to add it for that case.

Using clang tools for the refactoring would certainly be a cleaner and more reproducible solution, the problem with that is that I almost have zero knowledge about the clang-refactor tools. I will have to consider if it is worth the extra time it takes to learn their libraries (I guess it most likely is). So far I have found only few examples on how to use the clang tools for refactoring in general.

**Comment by mihaipopescu** [comment] 2017-10-29 22:22
As you know, at its heat, uncrustify has a doubly linked list of `chunk_t`s (obviously implemented with pointers). Virtually all functions are processing of it's elements (pointers to these chunks). It needs this flexibility to be able to easily add or remove tokens when needed (like braces, etc).

Now, even if references happen to be implemented internally as pointers inside compilers the concepts cannot be interchanged as they are semantically very different. Not being null is one of reference's trait but they are essentially aliases of some other variables you would have to have preallocated. They are things in the stack whereas pointers work with the heap memory, where all chunks are living. I was thinking if you were to do this change, you would need to swap a lot between pointers and references (like when you take a temporary chunk and "work" with it)... that's why maybe at times it would imply allocating more memory and copying around.. that I don't know exactly, just a hunch. A concrete example is needed, maybe some actual experimentation. Did you tried doing it?

I don't know, I'm just telling my concerns to avoid wasting work for something (avoid `nullptr` checks) that can be achieved with simpler structures like the one I proposed from GSL (and/or static analysis). Now, you don't have to pull the entire GSL library, just the `not_null\<T\>` class if you want.

About clang refactoring tools, I agree they can be hard to learn (very steep learning curve) but they are powerful tools and rewarding once you get to use them efficiently. Maybe it's a personal option as I don't like a lot of manual work but the good thing is that the work can be reproduced by somebody else which can "refactor" their inflight PRs or ... just think about all the forks (including ours) to avoid resolving a lot of conflicts. It's almost the same thing as with the formatting but that's another discussion.

**Comment by jibsen** [comment] 2017-10-30 08:31
I've only handled a few of these crashes, but they were related to using the `prev`, `next`, or `next->next` pointers without checking if they were valid.

One possible way this could be avoided is to require the use of a function to get the next and previous elements, which either checks for null, or even forces a check in the code using it (think something like `bool get_next(chunkt_t **ptr);`, where the value returned in `ptr` can be used only if the function returns true).

Another option would be using macros to get the previous and next elements, which can add run-time checks in debug builds that can write meaningful error messages including line numbers. But that just helps debug the issue rather than attempt to fix it of course.

**Comment by mihaipopescu** [comment] 2017-10-30 09:51
It's still going to be the same thing, just that the checks are moved to another place. I think @CDanU wants to remove all `nullptr` checks everywhere (or almost).

But I believe that code wins arguments (as in Facebook's "The Hacker Way" manifesto). So @CDanU I'm ok in doing or trying this out.

**Comment by CDanU** [comment] 2017-10-30 17:23
I mainly want to change the function signatures to use (const) references as much as possible. This has the benefit that some `nullptr` checks can be omitted, i.e. mainly those that check if the passed parameters are nullptr or not. 

I have two examples for this in my [references branch](https://github.com/CDanU/uncrustify/tree/references)

**Comment by KVic** [comment] 2017-10-30 17:34
I also think that pointers are evil. But Uncrustify is written in C-style, so replacing pointers to references will not help much. References should have been used from the very beginning, at an architectural level. Now, too many functions are used that return a pointer (chunk_get_xxx ()). What to do with them? I'm afraid it's too late to fix it, and better to direct efforts to improve functionality.

**Comment by mihaipopescu** [comment] 2017-10-30 23:58
Hum... but dereferencing those pointers is going to allocate memory on the stack as it's going to call `chunk_t.c-tor()` (which is not very lightweight as it's calling `reset()`). I think is not good enough to consider a good tradeoff between this penalty and avoiding some `nullptr` checks.

**Comment by CDanU** [comment] 2017-10-31 00:18
@mihaipopescu I am damn sure that in C/C++ dereferencing is not calling ctors, is not moving data from the heap to the stack or is doing anything with memory in any other way. I am somewhat confused.

Even though this indeed won't do too much, esp compared with the amount of changes, still I think that this is important. The chunk_get_xxx functions will still return pointers, but I plan to change them so that they will take in references.  
Thinking about the designing from the beginning. There will always be a list of tokens, and if there is a list there is always going to be a check for the end of that list. It wouldn't matter that much if it is a nullptr or something else.

In the mean time I am going to see how I can transform unc_text::c_str to be a const function. This is currently blocking me declaring the chunks as `const`.

**Comment by mihaipopescu** [comment] 2017-10-31 07:24
Yes, I was just thinking that could happen while you are converting back and forth between them or when you would want to reuse one variable as in a big function calling multiple functions with references.

`const`-correctness is nice to get afterwards but it could also be a double edge sword as you could probably end up doing some `const_cast<T>`s around.

Keep us posted with your findings.

**Comment by mihaipopescu** [comment] 2017-10-31 10:27
@CDanU Yes, ok. I see what you are saying. No, obviously dereferencing is not going to allocate memory on the stack if you are always using aliases unless when you are using actual variables and when they will have to be passed-by-value. I was wrong being not specific confusing you.

But still, as I said earlier, because `chunk_t` is a doubly-linked list you would have a very hard time rewriting loops `while (pc=pc->next)`, things like `pc->next`, `pc->prev->prev` and still have to move the `nullptr` check earlier before dereferencing that pointer.

**Comment by KVic** [comment] 2017-10-31 11:14
@CDanU 
> The chunk_get_xxx functions will still return pointers, but I plan to change them so that they will take in references.

I think that pointers and references should not be mixed in the usual code. In the statement `pc = chunk_get_next (pc);` `pc` acts as an iterator, so it must be implemented as an iterator (wrapper over the `chunk_t *`), with the methods `bool get_next_xxx() / get_prev_xxx()` (`move_next_xxx() / move_prev_xxx()`), `bool is_valid()`, `chunk_t & chunk()` and so on. Also, it is necessary to distinguish in the code, where `pc` is the `chunk object`, and where the `chunk iterator`.

**Comment by mihaipopescu** [comment] 2017-10-31 11:55
Yeah, I think starting from bottom-up, by changing `chunk_t` to have proper iterators which can check themselves for null, would probably be the best way to go. What do you think?

**Comment by KVic** [comment] 2017-10-31 12:09
I think there's no need to change the `chunk_t`. It is better to make the iterator as a separate class, like a wrapper over a `chunk_t *`.

**Comment by gmaurel** [comment] 2017-11-01 17:10
It is fine to get so many opinions.
Let us go on and try to find the best solution for uncrustify.
A big number of PR to do that is not an obstacle!

**Closed** 2017-11-10 23:26 UTC
Labels: System
