### ISSUE TITLE
extra characters at tests/objective-c.test

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1457] opened 2017-11-26 17:45 UTC
@CDanU was are the extra characters at the end of lines:
 7: OC
11: OC
82: OC+

**Comment by CDanU** [comment] 2017-11-26 17:48
Do you mean [this](https://github.com/uncrustify/uncrustify/blob/f8290b59aff323565b4b568cb63b78d18f2795fb/tests/objective-c.test#L7) ones? They specify the  language (-l) used for the tests.

**Comment by gmaurel** [comment] 2017-11-26 18:05
OK. But using tests/run_tests.py I get an error for the test 50410

**Comment by CDanU** [comment] 2017-11-26 18:10
I get that too, it seems that that happened quite a while ago. I'll pinpoint that later.

**Comment by CDanU** [comment] 2017-12-06 15:32
I think the previously referenced commit is just made a bug visible, the commit on its own is OK.

The problem is here: [output.cpp:617-627](https://github.com/uncrustify/uncrustify/blob/a128cc0edfbd9844800702f69065a3a56a2c4b26/src/output.cpp#L617-L627). 
During `indent_text()` the `CT_COND_COLON` gets a 1 assigned to `pc->column_indent` at [indent.cpp:2252](https://github.com/uncrustify/uncrustify/blob/a128cc0edfbd9844800702f69065a3a56a2c4b26/src/indent.cpp#L2252). It should be something higher in order to execute the `output_to_column` function that adds the tabs.

**Comment by CDanU** [comment] 2017-12-07 16:48
close this one, I'll move it into a new issue

**Closed** 2017-12-07 16:55 UTC
Labels: System

**Comment by mihaipopescu** [comment] 2017-12-10 23:26
I actually like this idea. As we also have testing suites with names which are a non-language (like `staging.test` and `regression.test`) and it would be nice to have this override.
