### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [uncrustify/uncrustify#1939] opened 2018-07-29 15:36 UTC
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [backup_copy_file](https://github.com/uncrustify/uncrustify/blob/d396bffff8f0f62ca66777a3cd7133106f0d95b4/src/backup.cpp#L99)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [print_universal_indent_cfg](https://github.com/uncrustify/uncrustify/blob/224dd2e439948ff100e4badb38d952ad443cca73/src/universalindentgui.cpp#L22)

**Comment by mihaipopescu** [comment] 2018-07-30 08:37
Sure, what do you have in mind that is not already handled? Do you have an use-case that could benefit of extra safety?

**Comment by elfring** [comment] 2018-07-30 08:45
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by mihaipopescu** [comment] 2018-07-30 08:47
Sounds like a good proposal. Can you start a PR on this?

**Comment by elfring** [comment] 2018-07-30 08:55
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by mihaipopescu** [comment] 2018-07-30 09:53
Uncrustify is already using [Coverity](https://scan.coverity.com/projects/uncrustify) although now I realise that the file patterns are broken (*.c instead of *.cpp?). I just requested access or maybe @gmaurel can fix it.

OTOH, I don't understand what is your intention here with your last comment but I think it's getting out of scope for this issue.

**Comment by elfring** [comment] 2018-07-30 10:22
* Does [the analysis tool “Coverity”](https://scan.coverity.com/projects/uncrustify "Checking uncrustify code with Coverity") point also the source code places out which I found for further software development considerations?
* Can higher level development tools help to improve also this software implementation any more?

**Comment by mihaipopescu** [comment] 2018-07-30 13:34
That needs to be investigated as currently the tool reports defects erroneously but I'm pretty sure Coverity is good enough to detect those.

**Comment by elfring** [comment] 2018-07-30 13:39
:crystal_ball: Would you like to extend your software development tool box?

**Comment by mihaipopescu** [comment] 2018-07-30 17:25
Can you be more specific and please clarify what is the connection with this issue?

**Comment by elfring** [comment] 2018-07-30 17:33
I propose to let specific development tools fix questionable source code.
You know some tools while you might be still unfamiliar with other software transformation approaches (which I am trying to point out here).

**Comment by mihaipopescu** [comment] 2018-08-01 08:06
I think Coverity Scan should be enough for starters. Running or adding more analysers is never the problem. Doing anything about the results is the problem.

Also, static analysis warnings should come with severity levels to be able to properly prioritise among the other 200 opened issues.

Now, getting back to your issue, did you managed to reproduce it on your side? Can you tell what are the steps to reproduce it?

**Comment by elfring** [comment] 2018-08-01 08:32
I have got understanding difficulties with the enquiry for reproducibility when I am still trying to clarify software design possibilities to fix remaining ignorance of return values from some function calls.

**Comment by mihaipopescu** [comment] 2018-08-01 09:30
Ok, then we're waiting for that but it looks like you have set yourself solving problem that might not be real. Here, we're a bit more practical.

So unless you can prove the validity and severity of the issue raised, I guess we should probably close the issue. Do you agree? OTOH, we would gladly review a PR that fixes "the ignorance of return values" or a proposal with the new "software design possibilities". But until then, this issue is a non-issue for me.

At the same time, I understand that the two possible problems you reported were never in your intention to report, but instead you wanted to evangelise (to be on the same page with @CDanU) the philosophy of running static analysers (especially AspectC++). But as we've mentioned, we're not lacking that.

Btw, I have to ask, do you happen to work for AspectC++?

**Comment by elfring** [comment] 2018-08-01 10:42
>Here, we're a bit more practical.

Do you care for file output failures?


>… a proposal with the new "software design possibilities".

Can it be that pull requests will not really help with desired clarification of acceptable changes in this case?


>At the same time, I understand that the two possible problems you reported were never in your intention to report,

I pointed another open issue out from the affected source code.


>but instead you wanted to evangelise (…) the philosophy of running static analysers (especially AspectC++).

Your view can be partly appropriate.


>But as we've mentioned, we're not lacking that.

Gratis analysis tools can be nice, can't they? - But free software can matter more.


>Btw, I have to ask, do you happen to work for AspectC++?

No.

* I am unsure if a commercial relationship will evolve there (if you think in such a direction).
* But it can be determined from the public archives that I had a bit of influence also on corresponding software evolution for a moment.

**Comment by mihaipopescu** [comment] 2018-08-02 13:55
How do you propose to recover from a failed `fclose` or `fprintf` call? Cleanup functions like `fclose` are the perfect example of functions where there isn't much you can do to if they fail.

I've also asked you before what are the use-cases and how often are these happening in practice but you seem to avoid the question.

Again, from my point of view, the issues you are pointing are _non-issues_ for the current state of uncrustify (or at best something to be regarded with very low priority right now on the roadmap) and I think we should just close it.

@guy-maurel @CDanU @mwoehlke-kitware What do you guys think?

**Comment by elfring** [comment] 2018-08-02 14:18
>Cleanup functions like `fclose` are the perfect example of functions where there isn't much you can do to if they fail.

How do you think about a reaction like the following?
* Throw [a corresponding C++ exception](https://en.cppreference.com/w/cpp/error/runtime_error "Description for std::runtime_error").
* Select [a program error code](https://en.wikipedia.org/wiki/Exit_status#C_language "Description for program exit status").

**Comment by mwoehlke-kitware** [comment] 2018-08-02 14:20
> How do you propose to recover from a failed `fclose` or `fprintf` call?

I don't think you can "recover", per se, but I suppose it's plausible you could decide that the operation failed and either (try to) report that, or else abort the operation (e.g. if `backup_copy_file` fails, abort rather than replacing the input anyway).

Realistically, though, it's pretty rare that these would fail, so I don't see this as a priority. We have plenty of known formatting issues that are much more likely to be relevant to our users. (@elfring, I'd encourage you to submit PR's...)

**Comment by elfring** [comment] 2018-08-02 14:25
Can you get [any further software development ideas](https://en.wikipedia.org/wiki/Fault_injection "Description for the usage of fault injection") from the following command example?

```
elfring@Sonne:~> LANG=C echo X > /dev/full
bash: echo: write error: No space left on device
```

**Comment by gmaurel** [comment] 2018-08-06 13:50
We all wanted to make a better software!
But we are working on existing issue(s).
If you have any, please push it/them.
Push the source code, the configuration file, the expected output.
Better, if you have any proposal to solve that problem, please make a push request.
If not, please keep quiet. Thanks for it.

**Comment by arneforlie** [comment] 2018-08-12 14:07
Maintainers, I admire your patience and politeness!
To me, this looks like trolling; 10 comments and not a single word of substance.

I had a look at his profile, and other projects experience the same thing, for instance:
https://github.com/json-c/json-c/issues/440
https://github.com/curl/curl/issues/2838

If I were you, I would just close the issue!

**Comment by error0x404** [comment] 2018-08-16 11:12
OP is either a persistent troll or a bot. You are all extremely nice people judging by the fact that you haven't hurled words of abuse at them/it yet, but I agree with @arneforlie that the issue should be closed. If @elfring is human, then, dear sir, despite your spam, I commend you for keeping character for so long. Novelty accounts are far more often found on Reddit than on GitHub.

**Closed** 2018-08-24 11:04 UTC
