### ISSUE TITLE
C: [Feature Request] the local variables aligns within a functionand in the mean while no global variables align

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1097] opened 2017-04-06 05:22 UTC
[debug.txt](https://gist.github.com/andrewhit/462230f9e6b067dad5ccc73f39611e3f)

azhuang@pek2-office-04-dhcp52:~$ uncrustify -v
uncrustify 0.64.549-gfa51230

Firstly, "align_var_def_span=1" is set, no change to the below function prototype and the statitic/global variables.
```
# The span for aligning variable definitions (0=don't align)
align_var_def_span            = 1       # number
```
```c
#if (NGX_HAVE_INET6)
static ngx_int_t ngx_http_add_addrs6(ngx_conf_t *cf, ngx_http_port_t *hport,
    ngx_http_conf_addr_t *addr);

#endif

ngx_uint_t ngx_http_max_module;
ngx_http_output_header_filter_pt ngx_http_top_header_filter;

ngx_str_t ngx_http_html_default_types[] = {
    ngx_string("text/html"),
    ngx_null_string
};

static ngx_command_t ngx_http_commands[] = {

    { ngx_string("http"),
      NGX_MAIN_CONF | NGX_CONF_BLOCK | NGX_CONF_NOARGS,
      ngx_http_block,
      0,
      0,
      NULL },

    ngx_null_command
};
```
However within ngx_http_init_locations(), the variables, r and regex do not align with their above variables, like n, q, locations  and etc.  And this is not what I want.

```c
static ngx_int_t
ngx_http_init_locations(ngx_conf_t *cf, ngx_http_core_srv_conf_t *cscf,
    ngx_http_core_loc_conf_t *pclcf)
{
    ngx_uint_t                 n;
    ngx_queue_t               *q, *locations, *named, tail;
    ngx_http_core_loc_conf_t  *clcf;
    ngx_http_location_queue_t *lq;
    ngx_http_core_loc_conf_t **clcfp;

#if (NGX_PCRE)
    ngx_uint_t   r;
    ngx_queue_t *regex;
#endif
```
Then "align_var_def_span=2" and the same above result was gotten. 

Then "align_var_def_span=3" gave me some what I want and some what I do not want.
```
# The span for aligning variable definitions (0=don't align)
align_var_def_span            = 3       # number
```
This is what I want, r and regex align with their above variables.

```c
static ngx_int_t
ngx_http_init_locations(ngx_conf_t *cf, ngx_http_core_srv_conf_t *cscf,
    ngx_http_core_loc_conf_t *pclcf)
{
    ngx_uint_t                 n;
    ngx_queue_t               *q, *locations, *named, tail;
    ngx_http_core_loc_conf_t  *clcf;
    ngx_http_location_queue_t *lq;
    ngx_http_core_loc_conf_t **clcfp;

#if (NGX_PCRE)
    ngx_uint_t                 r;
    ngx_queue_t               *regex;
#endif
```
But I do not want the global or static variables align together.
```c
#if (NGX_HAVE_INET6)
static ngx_int_t ngx_http_add_addrs6(ngx_conf_t *cf, ngx_http_port_t *hport,
    ngx_http_conf_addr_t *addr);

#endif

ngx_uint_t                       ngx_http_max_module;
ngx_http_output_header_filter_pt ngx_http_top_header_filter;

ngx_str_t                        ngx_http_html_default_types[] = {
    ngx_string("text/html"),
    ngx_null_string
};

static ngx_command_t             ngx_http_commands[] = {

    { ngx_string("http"),
      NGX_MAIN_CONF | NGX_CONF_BLOCK | NGX_CONF_NOARGS,
      ngx_http_block,
      0,
      0,
      NULL },

    ngx_null_command
};
```

**Comment by CDanU** [comment] 2017-04-06 14:49
> Then "align_var_def_span=2" and the same above result was gotten.
>
> Then "align_var_def_span=3" gave me some what I want and some what I do not want.

Yes that is the intended behavior:
From 
```
ngx_http_core_loc_conf_t **clcfp;
``` 
at the 3rd (<=n) line commes:
 ```
ngx_uint_t   r;
```

The same happens on  your bottom example:
From:
```
ngx_http_output_header_filter_pt ngx_http_top_header_filter;
```

on the 2nd line:
```
ngx_str_t                        </pre>ngx_http_html_default_types[] = { ..... };
```

and from that (I assume that it starts counting here from the closing brace), on the 2nd line:
```
static ngx_command_t             ngx_http_commands[] = {
```

There is nothing there that exempts globals or statics from `align_var_def_span`. You could play around with `align_var_def_thresh`, it additionally limits the aligning based on the column pos.

**Comment by andrewhit** [comment] 2017-04-07 02:59
Thanks!

Today I tried some values for ```align_var_def_thresh``` and did not get what I expected.

Anyway it should be a feature request as you confirmed.

**Closed** 2017-04-26 17:16 UTC
Labels: C and C++11
